
server:
  port: 8080

spring:
  application:
    name: gateway-api
  profiles:
    active: local

  cloud:
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: aolive-api
          uri: lb://aolive-api
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1