
server:
  port: 8080

spring:
  application:
    name: gateway-api

  cloud:
    gateway:
      enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: aolive-api
          uri: http://localhost:8081
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8079/eureka

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${spring.profiles.active}


